version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: navigator_new
      MYSQL_ROOT_PASSWORD: Av4936754
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 navigator.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=navigator.navigator.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A navigator worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=navigator.navigator.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A navigator beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=navigator.navigator.settings
      - CELERY_BROKER_URL=redis://redis:6379/0



volumes:
  mysql_data: